"""
CoT and CoT-SC baseline (Module 1 / first row of configs/base.yaml's
`baselines` list: "cot", "cot_sc5").

Design decision — sample once at max N, slice for every k
-----------------------------------------------------------
CoT-SC (Wang et al., 2023 — the DIGRA paper's own CoT-SC baseline,
[38] in its references) independently samples N reasoning paths from a
neutral prompt (NO gold answer, NO few-shot examples — this must NOT
reuse the response pools built by scripts/01_build_pools.py /
src/data/pool_generation.py, since those pools are seeded: their
"correct_texts" are, for a portion of questions, generated by giving the
model the gold answer in-context per Appendix B-3 step 3. Reusing them
here would silently inflate CoT-SC's accuracy relative to what the paper
actually reports for it) and takes the self-consistent (plurality) vote.

Rather than pick one N up front, `run_cot_sc` generates `n_samples_max`
completions in a single `llm.generate(..., n=n_samples_max)` call (the
model doesn't know N in advance, so every ordering is exchangeable) and
stores every raw sample. `majority_vote(samples, k)` then recomputes the
vote from just the first k of those stored samples. This gets both the
paper's main-table number (k=5) and a full accuracy-vs-sampling-count
sweep (paper's Fig. 5) from one generation pass — no re-generation, and
no extra GPU time spent for the sweep.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Optional

from src.agents.prompts import build_neutral_prompt
from src.llm.client import LLMClient
from src.metrics.grading import extract_final_answer, is_correct, normalize_answer
from src.metrics.text_metrics import exact_match, token_f1


@dataclass
class CotSample:
    """One raw generated sample plus its graded answer."""

    text: str
    extracted_answer: str
    is_correct: bool
    is_invalid: bool          # extraction produced an empty/unparseable answer
    em: bool
    f1: float
    n_tokens: Optional[int] = None   # None if logprobs weren't requested (see cot_sc.py docstring)


@dataclass
class VoteResult:
    """Self-consistency vote over the first k samples of a CotSCResult."""

    k: int
    majority_answer: str
    majority_is_correct: bool
    majority_vote_share: float       # fraction of the k samples agreeing with the winning answer
    vote_entropy: float              # Shannon entropy (nats) over the answer-cluster distribution
    n_unique_answers: int
    n_invalid: int
    invalid_rate: float


@dataclass
class CotSCResult:
    question_id: str
    dataset: str
    model: str
    gold_answer: str
    gold_answer_alternatives: list
    n_samples_requested: int
    samples: list                    # list[CotSample], length == n_samples_requested
    latency_seconds: float           # wall-clock time of the single generate() call
    seed: int


def run_cot_sc(
    llm: LLMClient,
    question_id: str,
    dataset: str,
    model_name: str,
    question: str,
    gold_answer: str,
    n_samples_max: int,
    gold_answer_alternatives: Optional[list] = None,
    seed: int = 0,
    max_tokens: int = 300,
    temperature: float = 1.0,
    top_p: float = 1.0,
    top_k: int = 50,
    logprobs_topk: Optional[int] = None,
) -> CotSCResult:
    """
    Generate `n_samples_max` independent CoT completions for one question
    (single batched `llm.generate` call, matching
    src/agents/debate.py's `generate_round_one_standard` pattern for
    round-1 "standard" generation — same neutral prompt, same sampling
    contract), grade each one, and return every sample so the caller can
    compute CoT (k=1) or CoT-SC(k=N) accuracy/consensus metrics for any
    k <= n_samples_max without any further model calls.

    `logprobs_topk`: pass through configs/base.yaml's
    generation.logprobs_topk if you want per-sample token counts (via
    len(token_logprobs)) for the cost/token metrics in the project
    checklist; None skips this (cheaper, and correct for FakeLLMClient
    tests that don't populate token_logprobs).
    """
    gold_answer_alternatives = gold_answer_alternatives or []
    prompt = build_neutral_prompt(question)

    start = time.perf_counter()
    results = llm.generate(
        prompt,
        n=n_samples_max,
        seed=seed,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        logprobs_topk=logprobs_topk,
    )
    latency = time.perf_counter() - start

    if len(results) != n_samples_max:
        raise RuntimeError(
            f"Expected {n_samples_max} CoT-SC samples from LLMClient for "
            f"question_id={question_id!r}, got {len(results)}."
        )

    samples = []
    for r in results:
        answer = extract_final_answer(r.text)
        invalid = normalize_answer(answer) == ""
        samples.append(
            CotSample(
                text=r.text,
                extracted_answer=answer,
                is_correct=is_correct(answer, gold_answer, gold_answer_alternatives),
                is_invalid=invalid,
                em=exact_match(answer, gold_answer, gold_answer_alternatives),
                f1=token_f1(answer, gold_answer, gold_answer_alternatives),
                n_tokens=(len(r.token_logprobs) if r.token_logprobs is not None else None),
            )
        )

    return CotSCResult(
        question_id=question_id,
        dataset=dataset,
        model=model_name,
        gold_answer=gold_answer,
        gold_answer_alternatives=gold_answer_alternatives,
        n_samples_requested=n_samples_max,
        samples=samples,
        latency_seconds=latency,
        seed=seed,
    )


def majority_vote(result: CotSCResult, k: int) -> VoteResult:
    """
    Self-consistency vote (Wang et al., 2023) over the FIRST k samples of
    `result` (k <= result.n_samples_requested; k=1 reduces exactly to
    plain CoT — a single sample, "majority" of one).

    Clustering is by normalized-answer string equality (grading.
    normalize_answer), matching how src/metrics/propagation_metrics.py's
    compute_final_accuracy already clusters majority votes elsewhere in
    this project, so "majority" means the same thing everywhere.

    An invalid (unparseable/empty) extracted answer is its own cluster
    key (the empty string) rather than being dropped — a question where
    every sample failed to parse should surface as invalid_rate=1.0 and
    a losing/never-winning empty-string cluster, not silently vanish from
    the vote.
    """
    if k < 1 or k > len(result.samples):
        raise ValueError(f"k={k} out of range for {len(result.samples)} samples")

    subset = result.samples[:k]
    groups: dict = {}
    for s in subset:
        key = normalize_answer(s.extracted_answer)
        groups.setdefault(key, []).append(s)

    majority_key = max(groups, key=lambda key: len(groups[key]))
    majority_samples = groups[majority_key]
    majority_share = len(majority_samples) / k

    # Ties broken by "any sample in the winning normalized-answer cluster
    # that is graded correct counts the cluster as correct" — every sample
    # in a cluster shares the same normalized answer, so grading is
    # actually constant within a cluster in practice; using any() here is
    # a defensive fallback, not a real tie-break, in case grading somehow
    # disagreed within an identical normalized string.
    majority_correct = any(s.is_correct for s in majority_samples)

    n_invalid = sum(1 for s in subset if s.is_invalid)

    probs = [len(v) / k for v in groups.values()]
    import math
    entropy = -sum(p * math.log(p) for p in probs if p > 0)

    return VoteResult(
        k=k,
        majority_answer=majority_samples[0].extracted_answer,
        majority_is_correct=majority_correct,
        majority_vote_share=majority_share,
        vote_entropy=entropy,
        n_unique_answers=len(groups),
        n_invalid=n_invalid,
        invalid_rate=n_invalid / k,
    )
